(define (domain meal_preparation)
  (:requirements
    :strips
    :typing
    :equality
    :negative-preconditions
    :disjunctive-preconditions
    :universal-preconditions
    :conditional-effects
    :action-costs
    :numeric-fluents
  )

  (:types
    robot meal ingredient approach_target - object
    location delivery_target - approach_target
  )

  (:constants
    bedside_table_left bedside_table_right - delivery_target
    sandwich salad hot_meal - meal
  )

  (:predicates
    (at ?r - robot ?l - location)
    (connected ?from ?to - location)
    (meal_to_prepare ?m - meal)
    (meal_chosen ?r - robot)
    (requires_cooking ?m - meal)
    (cold_meal ?m - meal)

    (pantry-location ?l - location)
    (fridge-location ?l - location)
    (prep-station-location ?l - location)
    (cooking-station ?l - location)
    (quality-check-location ?l - location)
    (charger-location ?l - location)
    (main-charger ?l - location)
    (backup-charger ?l - location)
    (patient-location ?l - location)
    (patient-left-location ?l - location)
    (patient-right-location ?l - location)
    (required_ingredient ?m - meal ?i - ingredient)
    (ingredient_available ?l - location ?i - ingredient)
    (collected_ingredient ?r - robot ?i - ingredient)
    (missing_ingredient ?r - robot ?i - ingredient)
    (expired_ingredient ?r - robot ?i - ingredient)
    (wrong_ingredient ?r - robot ?i - ingredient)
    (allergen_present ?r - robot ?i - ingredient)
    (ingredients_checked ?r - robot)
    (ingredients_safe ?r - robot ?m - meal)

    (workspace-clean ?r - robot)
    (robot-hands-clean ?r - robot)
    (cross-contamination-risk ?r - robot)

    (ingredients_washed ?r - robot)
    (ingredients_chopped ?r - robot)
    (meal_cooked ?r - robot)
    (ready_for_quality ?r - robot)
    (cooking_level_checked ?r - robot)
    (meal_palatable ?r - robot)
    (meal_assembled ?r - robot)

    (can_be_deliverable ?r - robot)
    (delivered ?r - robot)
  )

  (:functions
    (stage_cost)
    (total_time)
    (discrete_steps)

    (loc-x ?l - location)
    (loc-y ?l - location)
    (nav-time ?from ?to - location)
    (nav-battery ?from ?to - location)
    (nearest-charger-battery ?l - location)
    (location-safety ?l - location)
    (approach-feature ?x - approach_target)
    (proximity-feature ?l - location)

    ; w0=time, w1=safety, w2=battery, w3=proximity, w4=approach.
    (w0 ?r - robot)
    (w1 ?r - robot)
    (w2 ?r - robot)
    (w3 ?r - robot)
    (w4 ?r - robot)

    (battery-soc ?r - robot)

    (collect_duration)
    (check_duration)
    (sanitize_duration)
    (wash_duration)
    (chop_duration)
    (cook_duration)
    (assemble_duration)
    (deliver-time)
    (duration-recharge)

    (battery-collect_ingredient)
    (battery-check_ingredients)
    (battery-sanitize_workspace)
    (battery-wash_ingredients)
    (battery-chop_ingredients)
    (battery-cook_meal)
    (battery-check_cooking_level)
    (battery-check_palatability)
    (battery-assembla)
    (battery-deliver_on_bedside_table)
  )

  (:action choose_sandwich
    :parameters (?r - robot ?m - meal)
    :precondition (and
      (not (meal_chosen ?r))
      (= ?m sandwich)
    )
    :effect (and
      (meal_chosen ?r)
      (meal_to_prepare ?m)
      (increase (discrete_steps) 1)
    )
  )

  (:action choose_salad
    :parameters (?r - robot ?m - meal)
    :precondition (and
      (not (meal_chosen ?r))
      (= ?m salad)
    )
    :effect (and
      (meal_chosen ?r)
      (meal_to_prepare ?m)
      (increase (discrete_steps) 1)
    )
  )

  (:action choose_hot_meal
    :parameters (?r - robot ?m - meal)
    :precondition (and
      (not (meal_chosen ?r))
      (= ?m hot_meal)
    )
    :effect (and
      (meal_chosen ?r)
      (meal_to_prepare ?m)
      (increase (discrete_steps) 1)
    )
  )

  (:action go_to_pantry
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (connected ?from ?to)
      (pantry-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (* (w2 ?r) (nav-battery ?from ?to)))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_fridge
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (connected ?from ?to)
      (fridge-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (* (w2 ?r) (nav-battery ?from ?to)))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_prep_station
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (connected ?from ?to)
      (prep-station-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (* (w2 ?r) (nav-battery ?from ?to)))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_cooking_station
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (connected ?from ?to)
      (cooking-station ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (* (w2 ?r) (nav-battery ?from ?to)))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_quality_check
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (connected ?from ?to)
      (quality-check-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (* (w2 ?r) (nav-battery ?from ?to)))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_charge_main
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (charger-location ?to)
      (main-charger ?to)
      (not (= ?from ?to))
      (>= (battery-soc ?r) (nav-battery ?from ?to))
      (not (delivered ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_charge_backup
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (charger-location ?to)
      (backup-charger ?to)
      (not (= ?from ?to))
      (>= (battery-soc ?r) (nav-battery ?from ?to))
      (not (delivered ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action approach_to_left_side
    :parameters (?r - robot ?m - meal ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (meal_to_prepare ?m)
      (patient-location ?to)
      (patient-left-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to))
          (+ (battery-deliver_on_bedside_table) (nearest-charger-battery ?to)))
      (or (meal_cooked ?r) (not (requires_cooking ?m)))
      (meal_palatable ?r)
      (meal_assembled ?r)
      (not (delivered ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (can_be_deliverable ?r)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action approach_to_right_side
    :parameters (?r - robot ?m - meal ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (meal_to_prepare ?m)
      (patient-location ?to)
      (patient-right-location ?to)
      (not (= ?from ?to))
      (or (meal_cooked ?r) (not (requires_cooking ?m)))
      (meal_palatable ?r)
      (meal_assembled ?r)
      (not (delivered ?r))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to))
          (+ (battery-deliver_on_bedside_table) (nearest-charger-battery ?to)))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (can_be_deliverable ?r)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action collect_ingredient
    :parameters (?r - robot ?m - meal ?i - ingredient ?l - location)
    :precondition (and
      (at ?r ?l)
      (meal_to_prepare ?m)
      (required_ingredient ?m ?i)
      (ingredient_available ?l ?i)
      (not (collected_ingredient ?r ?i))
      (> (battery-soc ?r) (+ (battery-collect_ingredient) (nearest-charger-battery ?l)))
    )
    :effect (and
      (collected_ingredient ?r ?i)
      (not (missing_ingredient ?r ?i))
      (increase (total_time) (collect_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-collect_ingredient))
      (increase (stage_cost) (+ (* (w0 ?r) (collect_duration)) (* (w2 ?r) (battery-collect_ingredient))))
      (when (< (- (battery-soc ?r) (battery-collect_ingredient)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-collect_ingredient)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action check_ingredients
    :parameters (?r - robot ?m - meal ?l - location)
    :precondition (and
      (at ?r ?l)
      (meal_to_prepare ?m)
      (not (ingredients_checked ?r))
      (forall (?i - ingredient) (or (not (required_ingredient ?m ?i)) (collected_ingredient ?r ?i)))
      (forall (?i - ingredient) (or (not (required_ingredient ?m ?i)) (not (missing_ingredient ?r ?i))))
      (forall (?i - ingredient) (or (not (required_ingredient ?m ?i)) (not (wrong_ingredient ?r ?i))))
      (forall (?i - ingredient) (or (not (required_ingredient ?m ?i)) (not (expired_ingredient ?r ?i))))
      (forall (?i - ingredient) (or (not (required_ingredient ?m ?i)) (not (allergen_present ?r ?i))))
      (> (battery-soc ?r) (+ (battery-check_ingredients) (nearest-charger-battery ?l)))
    )
    :effect (and
      (ingredients_checked ?r)
      (ingredients_safe ?r ?m)
      (increase (total_time) (check_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-check_ingredients))
      (increase (stage_cost) (+ (* (w0 ?r) (check_duration)) (* (w2 ?r) (battery-check_ingredients))))
      (when (< (- (battery-soc ?r) (battery-check_ingredients)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-check_ingredients)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action sanitize_workspace
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (or (prep-station-location ?l) (cooking-station ?l))
      (not (workspace-clean ?r))
      (> (battery-soc ?r) (+ (battery-sanitize_workspace) (nearest-charger-battery ?l)))
    )
    :effect (and
      (workspace-clean ?r)
      (robot-hands-clean ?r)
      (not (cross-contamination-risk ?r))
      (increase (total_time) (sanitize_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-sanitize_workspace))
      (increase (stage_cost) (+ (* (w0 ?r) (sanitize_duration)) (* (w2 ?r) (battery-sanitize_workspace))))
      (when (< (- (battery-soc ?r) (battery-sanitize_workspace)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-sanitize_workspace)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action wash_ingredients
    :parameters (?r - robot ?m - meal ?l - location)
    :precondition (and
      (at ?r ?l)
      (prep-station-location ?l)
      (meal_to_prepare ?m)
      (ingredients_safe ?r ?m)
      (workspace-clean ?r)
      (robot-hands-clean ?r)
      (not (ingredients_washed ?r))
      (> (battery-soc ?r) (+ (battery-wash_ingredients) (nearest-charger-battery ?l)))
    )
    :effect (and
      (ingredients_washed ?r)
      (increase (total_time) (wash_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-wash_ingredients))
      (increase (stage_cost) (+ (* (w0 ?r) (wash_duration)) (* (w2 ?r) (battery-wash_ingredients))))
      (when (< (- (battery-soc ?r) (battery-wash_ingredients)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-wash_ingredients)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action chop_ingredients
    :parameters (?r - robot ?m - meal ?l - location)
    :precondition (and
      (at ?r ?l)
      (prep-station-location ?l)
      (meal_to_prepare ?m)
      (ingredients_safe ?r ?m)
      (ingredients_washed ?r)
      (workspace-clean ?r)
      (robot-hands-clean ?r)
      (not (cross-contamination-risk ?r))
      (not (ingredients_chopped ?r))
      (> (battery-soc ?r) (+ (battery-chop_ingredients) (nearest-charger-battery ?l)))
    )
    :effect (and
      (ingredients_chopped ?r)
      (when (cold_meal ?m) (ready_for_quality ?r))
      (increase (total_time) (chop_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-chop_ingredients))
      (increase (stage_cost) (+ (* (w0 ?r) (chop_duration)) (* (w2 ?r) (battery-chop_ingredients))))
      (when (< (- (battery-soc ?r) (battery-chop_ingredients)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-chop_ingredients)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action cook_meal
    :parameters (?r - robot ?m - meal ?l - location)
    :precondition (and
      (at ?r ?l)
      (cooking-station ?l)
      (meal_to_prepare ?m)
      (requires_cooking ?m)
      (ingredients_safe ?r ?m)
      (ingredients_washed ?r)
      (ingredients_chopped ?r)
      (workspace-clean ?r)
      (robot-hands-clean ?r)
      (not (cross-contamination-risk ?r))
      (not (meal_cooked ?r))
      (> (battery-soc ?r) (+ (battery-cook_meal) (nearest-charger-battery ?l)))
    )
    :effect (and
      (meal_cooked ?r)
      (ready_for_quality ?r)
      (increase (total_time) (cook_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-cook_meal))
      (increase (stage_cost) (+ (* (w0 ?r) (cook_duration)) (* (w2 ?r) (battery-cook_meal))))
      (when (< (- (battery-soc ?r) (battery-cook_meal)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-cook_meal)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action check_cooking_level
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (quality-check-location ?l)
      (ready_for_quality ?r)
      (not (cooking_level_checked ?r))
      (> (battery-soc ?r) (+ (battery-check_cooking_level) (nearest-charger-battery ?l)))
    )
    :effect (and
      (cooking_level_checked ?r)
      (increase (total_time) (check_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-check_cooking_level))
      (increase (stage_cost) (+ (* (w0 ?r) (check_duration)) (* (w2 ?r) (battery-check_cooking_level))))
      (when (< (- (battery-soc ?r) (battery-check_cooking_level)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-check_cooking_level)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action check_palatability
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (quality-check-location ?l)
      (ready_for_quality ?r)
      (cooking_level_checked ?r)
      (not (meal_palatable ?r))
      (> (battery-soc ?r) (+ (battery-check_palatability) (nearest-charger-battery ?l)))
    )
    :effect (and
      (meal_palatable ?r)
      (increase (total_time) (check_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-check_palatability))
      (increase (stage_cost) (+ (* (w0 ?r) (check_duration)) (* (w2 ?r) (battery-check_palatability))))
      (when (< (- (battery-soc ?r) (battery-check_palatability)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-check_palatability)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action assembla
    :parameters (?r - robot ?m - meal ?l - location)
    :precondition (and
      (at ?r ?l)
      (quality-check-location ?l)
      (meal_to_prepare ?m)
      (ingredients_safe ?r ?m)
      (ready_for_quality ?r)
      (cooking_level_checked ?r)
      (meal_palatable ?r)
      (not (meal_assembled ?r))
      (> (battery-soc ?r) (+ (battery-assembla) (nearest-charger-battery ?l)))
    )
    :effect (and
      (meal_assembled ?r)
      (increase (total_time) (assemble_duration))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-assembla))
      (increase (stage_cost) (+ (* (w0 ?r) (assemble_duration)) (* (w2 ?r) (battery-assembla))))
      (when (< (- (battery-soc ?r) (battery-assembla)) 0.15) (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (battery-assembla)) 0.25) (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action deliver_on_bedside_table_left
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (patient-location ?l)
      (patient-left-location ?l)
      (ready_for_quality ?r)
      (meal_palatable ?r)
      (meal_assembled ?r)
      (can_be_deliverable ?r)
      (not (delivered ?r))
      (>= (battery-soc ?r) (battery-deliver_on_bedside_table))
    )
    :effect (and
      (increase (total_time) (deliver-time))
      (increase (discrete_steps) 1)
      (delivered ?r)
      (decrease (battery-soc ?r) (battery-deliver_on_bedside_table))
      (increase (stage_cost)
        (+ (* (w0 ?r) (deliver-time))
           (+ (* (w2 ?r) (battery-deliver_on_bedside_table))
              (* (w4 ?r) (approach-feature bedside_table_left)))))
    )
  )

  (:action deliver_on_bedside_table_right
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (patient-location ?l)
      (patient-right-location ?l)
      (ready_for_quality ?r)
      (meal_palatable ?r)
      (meal_assembled ?r)
      (can_be_deliverable ?r)
      (not (delivered ?r))
      (>= (battery-soc ?r) (battery-deliver_on_bedside_table))
    )
    :effect (and
      (increase (total_time) (deliver-time))
      (increase (discrete_steps) 1)
      (delivered ?r)
      (decrease (battery-soc ?r) (battery-deliver_on_bedside_table))
      (increase (stage_cost)
        (+ (* (w0 ?r) (deliver-time))
           (+ (* (w2 ?r) (battery-deliver_on_bedside_table))
              (* (w4 ?r) (approach-feature bedside_table_right)))))
    )
  )

  (:action recharge
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (charger-location ?l)
      (not (delivered ?r))
    )
    :effect (and
      (increase (total_time) (duration-recharge))
      (increase (discrete_steps) 1)
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-recharge))))
      (assign (battery-soc ?r) 1.0)
    )
  )
)

