(define (domain medication_delivery)
  (:requirements :strips :typing :equality :negative-preconditions :action-costs :numeric-fluents :conditional-effects)

  (:types
    robot medicine supplement approach_target - object
    location delivery_target - approach_target
  )

  (:constants
    med_antibiotic med_analgesic med_insulin - medicine
    supp_vitamin_d supp_electrolyte supp_omega3 - supplement
    bedside_table_left bedside_table_right - delivery_target
  )

  (:predicates
    (at ?r - robot ?l - location)

    (pharmacy-location ?l - location)
    (pharmacy-north-location ?l - location)
    (pharmacy-south-location ?l - location)
    (supply-location ?l - location)
    (supply-a-location ?l - location)
    (supply-b-location ?l - location)
    (charger-location ?l - location)
    (main-charger ?l - location)
    (backup-charger ?l - location)
    (patient-location ?l - location)
    (patient-left-location ?l - location)
    (patient-right-location ?l - location)

    (requested-medicine ?m - medicine)
    (requested-supplement ?s - supplement)

    (has-medication ?r - robot)
    (has-supplement ?r - robot)
    (carrying-medicine ?r - robot ?m - medicine)
    (carrying-supplement ?r - robot ?s - supplement)
    (unchecked-medication ?r - robot)
    (unchecked-supplement ?r - robot)
    (correct-medication ?r - robot)
    (correct-supplement ?r - robot)
    (medicine-recollect-required ?r - robot)
    (supplement-recollect-required ?r - robot)
    (can_be_deliverable ?r - robot)
    (delivered ?r - robot)

  )

  (:functions
    (stage_cost)
    (total_time)
    (discrete_steps)
    (loc-x ?l - location)
    (loc-y ?l - location)
    ; Action durations. These are zero-arity numeric fluents so the replanner can update them.

    (duration-collect-medication)
    (duration-collect-supplement)
    (duration-check-medication)
    (duration-check-supplement)
    (duration-recharge)
    (duration-put_down)

    ; Battery used by in-place actions. Movement battery is represented by nav-battery.
    (battery-collect-medication)
    (battery-collect-supplement)
    (battery-check-medication)
    (battery-check-supplement)
    (battery-put_down)
    (battery-deliver_on_bedside_table)

    ; w0..w4 are replanner-owned preference weights for stage_cost.
    ; The domain uses them in the scalar product but never modifies them.
    (battery-soc ?r - robot)
    (w0 ?r - robot)
    (w1 ?r - robot)
    (w2 ?r - robot)
    (w3 ?r - robot)
    (w4 ?r - robot)

    ; Feature deltas follow calculate_action_cost_Medication_flattened and are NOT scaled.
    (nav-time ?from ?to - location)
    (nav-battery ?from ?to - location)
    (nearest-charger-battery ?l - location)
    (location-safety ?l - location)
    (approach-feature ?x - approach_target)
    (proximity-feature ?l - location)
    (deliver-time)
  )

  (:action go_to_pharmacy_north
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (pharmacy-location ?to)
      (pharmacy-north-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
      (not (unchecked-medication ?r))
      (not (unchecked-supplement ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (not (delivered ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_pharmacy_south
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (pharmacy-location ?to)
      (pharmacy-south-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
      (not (unchecked-medication ?r))
      (not (unchecked-supplement ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (not (delivered ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_supply_a
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (supply-location ?to)
      (supply-a-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
      (not (unchecked-medication ?r))
      (not (unchecked-supplement ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (not (delivered ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_supply_b
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (supply-location ?to)
      (supply-b-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
      (not (unchecked-medication ?r))
      (not (unchecked-supplement ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (not (delivered ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_charge_main
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (charger-location ?to)
      (main-charger ?to)
      (not (= ?from ?to))
      (>= (battery-soc ?r) (nav-battery ?from ?to))
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action go_to_charge_backup
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (charger-location ?to)
      (backup-charger ?to)
      (not (= ?from ?to))
      (>= (battery-soc ?r) (nav-battery ?from ?to))
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action approach_left_to_bed
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (patient-location ?to)
      (patient-left-location ?to)
      (not (= ?from ?to))
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
      (not (unchecked-medication ?r))
      (not (unchecked-supplement ?r))
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (has-medication ?r)
      (has-supplement ?r)
      (correct-medication ?r)
      (correct-supplement ?r)
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (can_be_deliverable ?r)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action approach_right_to_bed
    :parameters (?r - robot ?from - location ?to - location)
    :precondition (and
      (at ?r ?from)
      (patient-location ?to)
      (patient-right-location ?to)
      (not (= ?from ?to))
      (not (unchecked-medication ?r))
      (not (unchecked-supplement ?r))
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (has-medication ?r)
      (has-supplement ?r)
      (correct-medication ?r)
      (correct-supplement ?r)
      (>= (- (battery-soc ?r) (nav-battery ?from ?to)) (nearest-charger-battery ?to))
    )
    :effect (and
      (increase (total_time) (nav-time ?from ?to))
      (increase (discrete_steps) 1)
      (not (at ?r ?from))
      (at ?r ?to)
      (can_be_deliverable ?r)
      (decrease (battery-soc ?r) (nav-battery ?from ?to))
      (increase (stage_cost)
        (+ (* (w0 ?r) (nav-time ?from ?to))
           (+ (* (w1 ?r) (location-safety ?to))
              (+ (* (w2 ?r) (nav-battery ?from ?to))
                 (+ (* (w3 ?r) (proximity-feature ?to))
                    (* (w4 ?r) (approach-feature ?to)))))))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.15)
        (increase (stage_cost) (* (w2 ?r) 0.5)))
      (when (< (- (battery-soc ?r) (nav-battery ?from ?to)) 0.25)
        (increase (stage_cost) (* (w2 ?r) 0.2)))
    )
  )

  (:action collect_med_antibiotic
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (pharmacy-location ?l)
      (not (has-medication ?r))
      (not (delivered ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r)
         (+ (battery-collect-medication)
            (+ (battery-check-medication)
               (+ (battery-put_down) (nearest-charger-battery ?l)))))
    )
    :effect (and
      (increase (total_time) (duration-collect-medication))
      (increase (discrete_steps) 1)
      (has-medication ?r)
      (carrying-medicine ?r med_antibiotic)
      (unchecked-medication ?r)
      (not (correct-medication ?r))
      (not (medicine-recollect-required ?r))
      (decrease (battery-soc ?r) (battery-collect-medication))
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-collect-medication))
           (* (w2 ?r) (battery-collect-medication))))
    )
  )

  (:action collect_med_analgesic
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (pharmacy-location ?l)
      (not (has-medication ?r))
      (not (delivered ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r)
         (+ (battery-collect-medication)
            (+ (battery-check-medication)
               (+ (battery-put_down) (nearest-charger-battery ?l)))))
    )
    :effect (and
      (increase (total_time) (duration-collect-medication))
      (increase (discrete_steps) 1)
      (has-medication ?r)
      (carrying-medicine ?r med_analgesic)
      (unchecked-medication ?r)
      (not (correct-medication ?r))
      (not (medicine-recollect-required ?r))
      (decrease (battery-soc ?r) (battery-collect-medication))
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-collect-medication))
           (* (w2 ?r) (battery-collect-medication))))
    )
  )

  (:action collect_med_insulin
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (pharmacy-location ?l)
      (not (has-medication ?r))
      (not (delivered ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r)
         (+ (battery-collect-medication)
            (+ (battery-check-medication)
               (+ (battery-put_down) (nearest-charger-battery ?l)))))
    )
    :effect (and
      (increase (total_time) (duration-collect-medication))
      (increase (discrete_steps) 1)
      (has-medication ?r)
      (carrying-medicine ?r med_insulin)
      (unchecked-medication ?r)
      (not (correct-medication ?r))
      (not (medicine-recollect-required ?r))
      (decrease (battery-soc ?r) (battery-collect-medication))
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-collect-medication))
           (* (w2 ?r) (battery-collect-medication))))
    )
  )

  (:action collect_supp_vitamin_d
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (supply-location ?l)
      (not (has-supplement ?r))
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (> (battery-soc ?r)
         (+ (battery-collect-supplement)
            (+ (battery-check-supplement)
               (+ (battery-put_down) (nearest-charger-battery ?l)))))
    )
    :effect (and
      (increase (total_time) (duration-collect-supplement))
      (increase (discrete_steps) 1)
      (has-supplement ?r)
      (carrying-supplement ?r supp_vitamin_d)
      (unchecked-supplement ?r)
      (not (correct-supplement ?r))
      (not (supplement-recollect-required ?r))
      (decrease (battery-soc ?r) (battery-collect-supplement))
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-collect-supplement))
           (* (w2 ?r) (battery-collect-supplement))))
    )
  )

  (:action collect_supp_electrolyte
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (supply-location ?l)
      (not (has-supplement ?r))
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (> (battery-soc ?r)
         (+ (battery-collect-supplement)
            (+ (battery-check-supplement)
               (+ (battery-put_down) (nearest-charger-battery ?l)))))
    )
    :effect (and
      (increase (total_time) (duration-collect-supplement))
      (increase (discrete_steps) 1)
      (has-supplement ?r)
      (carrying-supplement ?r supp_electrolyte)
      (unchecked-supplement ?r)
      (not (correct-supplement ?r))
      (not (supplement-recollect-required ?r))
      (decrease (battery-soc ?r) (battery-collect-supplement))
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-collect-supplement))
           (* (w2 ?r) (battery-collect-supplement))))
    )
  )

  (:action collect_supp_omega3
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (supply-location ?l)
      (not (has-supplement ?r))
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (> (battery-soc ?r)
         (+ (battery-collect-supplement)
            (+ (battery-check-supplement)
               (+ (battery-put_down) (nearest-charger-battery ?l)))))
    )
    :effect (and
      (increase (total_time) (duration-collect-supplement))
      (increase (discrete_steps) 1)
      (has-supplement ?r)
      (carrying-supplement ?r supp_omega3)
      (unchecked-supplement ?r)
      (not (correct-supplement ?r))
      (not (supplement-recollect-required ?r))
      (decrease (battery-soc ?r) (battery-collect-supplement))
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-collect-supplement))
           (* (w2 ?r) (battery-collect-supplement))))
    )
  )

  (:action put_down_medicine
    :parameters (?r - robot ?l - location ?m - medicine)
    :precondition (and
      (at ?r ?l)
      (has-medication ?r)
      (carrying-medicine ?r ?m)
      (not (unchecked-medication ?r))
      (not (correct-medication ?r))
      (> (battery-soc ?r) (+ (battery-put_down) (nearest-charger-battery ?l)))

    )
    :effect (and
      (not (has-medication ?r))
      (not (carrying-medicine ?r ?m))
      (medicine-recollect-required ?r)
      (increase (total_time) (duration-put_down))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-put_down))
      (increase (stage_cost)
        (+ 100
           (+ (* (w0 ?r) (duration-put_down))
              (* (w2 ?r) (battery-put_down)))))
    )
  )

  (:action put_down_supplement
    :parameters (?r - robot ?l - location ?s - supplement)
    :precondition (and
      (at ?r ?l)
      (has-supplement ?r)
      (carrying-supplement ?r ?s)
      (not (unchecked-supplement ?r))
      (not (correct-supplement ?r))
      (> (battery-soc ?r) (+ (battery-put_down) (nearest-charger-battery ?l)))
    )
    :effect (and
      (not (has-supplement ?r))
      (not (carrying-supplement ?r ?s))
      (supplement-recollect-required ?r)
      (increase (total_time) (duration-put_down))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-put_down))
      (increase (stage_cost)
        (+ 100
           (+ (* (w0 ?r) (duration-put_down))
              (* (w2 ?r) (battery-put_down)))))
    )
  )

  (:action check_medication_correct
    :parameters (?r - robot ?l - location ?m - medicine)
    :precondition (and
      (at ?r ?l)
      (has-medication ?r)
      (carrying-medicine ?r ?m)
      (requested-medicine ?m)
      (unchecked-medication ?r)
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r) (+ (battery-check-medication) (nearest-charger-battery ?l)))
    )
    :effect (and
      (increase (total_time) (duration-check-medication))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-check-medication))
      (not (unchecked-medication ?r))
      (correct-medication ?r)
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-check-medication))
           (* (w2 ?r) (battery-check-medication))))
    )
  )

  (:action check_medication_wrong
    :parameters (?r - robot ?l - location ?m - medicine)
    :precondition (and
      (at ?r ?l)
      (has-medication ?r)
      (carrying-medicine ?r ?m)
      (not (requested-medicine ?m))
      (unchecked-medication ?r)
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r)
         (+ (battery-check-medication)
            (+ (battery-collect-medication) (nearest-charger-battery ?l))))
    )
    :effect (and
      (increase (total_time) (duration-check-medication))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-check-medication))
      (not (unchecked-medication ?r))
      (not (correct-medication ?r))
      (medicine-recollect-required ?r)
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-check-medication))
           (* (w2 ?r) (battery-check-medication))))
    )
  )

  (:action check_supplement_correct
    :parameters (?r - robot ?l - location ?s - supplement)
    :precondition (and
      (at ?r ?l)
      (has-supplement ?r)
      (carrying-supplement ?r ?s)
      (requested-supplement ?s)
      (unchecked-supplement ?r)
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r) (+ (battery-check-supplement) (nearest-charger-battery ?l)))
    )
    :effect (and
      (increase (total_time) (duration-check-supplement))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-check-supplement))
      (not (unchecked-supplement ?r))
      (correct-supplement ?r)
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-check-supplement))
           (* (w2 ?r) (battery-check-supplement))))
    )
  )

  (:action check_supplement_wrong
    :parameters (?r - robot ?l - location ?s - supplement)
    :precondition (and
      (at ?r ?l)
      (has-supplement ?r)
      (carrying-supplement ?r ?s)
      (not (requested-supplement ?s))
      (unchecked-supplement ?r)
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r)
         (+ (battery-check-supplement)
            (+ (battery-collect-supplement) (nearest-charger-battery ?l))))
    )
    :effect (and
      (increase (total_time) (duration-check-supplement))
      (increase (discrete_steps) 1)
      (decrease (battery-soc ?r) (battery-check-supplement))
      (not (unchecked-supplement ?r))
      (not (correct-supplement ?r))
      (supplement-recollect-required ?r)
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-check-supplement))
           (* (w2 ?r) (battery-check-supplement))))
    )
  )

  (:action deliver_on_bedside_table_left
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (patient-location ?l)
      (patient-left-location ?l)
      (has-medication ?r)
      (has-supplement ?r)
      (correct-medication ?r)
      (correct-supplement ?r)
      (can_be_deliverable ?r)
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r) (battery-deliver_on_bedside_table))
    )
    :effect (and
      (increase (total_time) (deliver-time))
      (increase (discrete_steps) 1)
      (delivered ?r)
      (decrease (battery-soc ?r) (battery-deliver_on_bedside_table))
      (increase (stage_cost)
        (+ (* (w0 ?r) (deliver-time))
           (+ (* (w2 ?r) (battery-deliver_on_bedside_table))
              (* (w4 ?r) (approach-feature bedside_table_left)))))
    )
  )

  (:action deliver_on_bedside_table_right
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (patient-location ?l)
      (patient-right-location ?l)
      (has-medication ?r)
      (has-supplement ?r)
      (correct-medication ?r)
      (correct-supplement ?r)
      (can_be_deliverable ?r)
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
      (> (battery-soc ?r) (battery-deliver_on_bedside_table))

    )
    :effect (and
      (increase (total_time) (deliver-time))
      (increase (discrete_steps) 1)
      (delivered ?r)
      (decrease (battery-soc ?r) (battery-deliver_on_bedside_table))
      (increase (stage_cost)
        (+ (* (w0 ?r) (deliver-time))
           (+ (* (w2 ?r) (battery-deliver_on_bedside_table))
              (* (w4 ?r) (approach-feature bedside_table_right)))))
    )
  )


  (:action recharge
    :parameters (?r - robot ?l - location)
    :precondition (and
      (at ?r ?l)
      (charger-location ?l)
      (not (delivered ?r))
      (not (medicine-recollect-required ?r))
      (not (supplement-recollect-required ?r))
    )
    :effect (and
      (increase (total_time) (duration-recharge))
      (increase (discrete_steps) 1)
      (increase (stage_cost)
        (+ (* (w0 ?r) (duration-recharge))))
      (assign (battery-soc ?r) 1.0)
    )
  )

)
