(define (problem meal_preparation_problem)
  (:domain meal_preparation)

  (:objects
    robot1 - robot
    home pantry fridge prep_station stove quality_check
    patient_bed_left patient_bed_right charge_main charge_backup - location
    bread nuts chicken vegetables - ingredient
  )

  (:init
    (= (stage_cost) 0)
    (= (total_time) 0)
    (= (discrete_steps) 0)

    ; Static coordinates for each modeled location.
    (= (loc-x home) 0.0000)
    (= (loc-y home) 0.0000)
    (= (loc-x pantry) -3.0000)
    (= (loc-y pantry) 15.0000)
    (= (loc-x fridge) -6.0000)
    (= (loc-y fridge) 17.5000)
    (= (loc-x prep_station) 0.0000)
    (= (loc-y prep_station) 20.0000)
    (= (loc-x stove) -3.0000)
    (= (loc-y stove) 20.5000)
    (= (loc-x quality_check) 3.0000)
    (= (loc-y quality_check) 21.0000)
    (= (loc-x patient_bed_left) 20.5000)
    (= (loc-y patient_bed_left) 12.0000)
    (= (loc-x patient_bed_right) 23.5000)
    (= (loc-y patient_bed_right) 10.0000)
    (= (loc-x charge_main) 3.0000)
    (= (loc-y charge_main) 5.0000)
    (= (loc-x charge_backup) 17.0000)
    (= (loc-y charge_backup) -18.0000)
    ; Directed navigation graph for this task instance.
    (connected home pantry)
    (connected home fridge)
    (connected pantry fridge)
    (connected pantry prep_station)
    (connected fridge prep_station)
    (connected prep_station quality_check)
    (connected prep_station stove)
    (connected stove quality_check)
    (connected quality_check patient_bed_left)
    (connected quality_check patient_bed_right)
    (connected charge_main pantry)
    (connected charge_main fridge)
    (connected charge_main prep_station)
    (connected charge_main stove)
    (connected charge_main quality_check)
    (connected charge_main patient_bed_left)
    (connected charge_main patient_bed_right)
    (connected charge_backup pantry)
    (connected charge_backup fridge)
    (connected charge_backup prep_station)
    (connected charge_backup stove)
    (connected charge_backup quality_check)
    (connected charge_backup patient_bed_left)
    (connected charge_backup patient_bed_right)

    ; Navigation resources: nav-battery = euclidean distance * 0.01;
    ; nav-time = ((distance / 1.5) * (1 + destination congestion)) / 60.
    (= (nav-time home pantry) 0.1955)
    (= (nav-battery home pantry) 0.1530)
    (= (nav-time home fridge) 0.2405)
    (= (nav-battery home fridge) 0.1850)
    (= (nav-time pantry fridge) 0.050767)
    (= (nav-battery pantry fridge) 0.039051)
    (= (nav-time pantry prep_station) 0.077746)
    (= (nav-battery pantry prep_station) 0.058310)
    (= (nav-time fridge prep_station) 0.086667)
    (= (nav-battery fridge prep_station) 0.065000)
    (= (nav-time prep_station stove) 0.042241)
    (= (nav-battery prep_station stove) 0.030414)
    (= (nav-time prep_station quality_check) 0.038653)
    (= (nav-battery prep_station quality_check) 0.031623)
    (= (nav-time stove quality_check) 0.073588)
    (= (nav-battery stove quality_check) 0.060208)
    (= (nav-time quality_check patient_bed_left) 0.218652)
    (= (nav-battery quality_check patient_bed_left) 0.196787)
    (= (nav-time quality_check patient_bed_right) 0.258498)
    (= (nav-battery quality_check patient_bed_right) 0.232648)
    (= (nav-time home charge_main) 0.064788)
    (= (nav-battery home charge_main) 0.058310)
    (= (nav-time home charge_backup) 0.275098)
    (= (nav-battery home charge_backup) 0.247588)
    (= (nav-time pantry charge_main) 0.129577)
    (= (nav-battery pantry charge_main) 0.116619)
    (= (nav-time pantry charge_backup) 0.428751)
    (= (nav-battery pantry charge_backup) 0.385876)
    (= (nav-time fridge charge_main) 0.171144)
    (= (nav-battery fridge charge_main) 0.154029)
    (= (nav-time fridge charge_backup) 0.469995)
    (= (nav-battery fridge charge_backup) 0.422995)
    (= (nav-time prep_station charge_main) 0.169967)
    (= (nav-battery prep_station charge_main) 0.152971)
    (= (nav-time prep_station charge_backup) 0.462548)
    (= (nav-battery prep_station charge_backup) 0.416293)
    (= (nav-time stove charge_main) 0.184675)
    (= (nav-battery stove charge_main) 0.166208)
    (= (nav-time stove charge_backup) 0.482055)
    (= (nav-battery stove charge_backup) 0.433849)
    (= (nav-time quality_check charge_main) 0.177778)
    (= (nav-battery quality_check charge_main) 0.160000)
    (= (nav-time quality_check charge_backup) 0.460408)
    (= (nav-battery quality_check charge_backup) 0.414367)
    (= (nav-time patient_bed_left charge_main) 0.209423)
    (= (nav-battery patient_bed_left charge_main) 0.188481)
    (= (nav-time patient_bed_left charge_backup) 0.335594)
    (= (nav-battery patient_bed_left charge_backup) 0.302035)
    (= (nav-time patient_bed_right charge_main) 0.234455)
    (= (nav-battery patient_bed_right charge_main) 0.211009)
    (= (nav-time patient_bed_right charge_backup) 0.319384)
    (= (nav-battery patient_bed_right charge_backup) 0.287446)
    (= (nav-time charge_main pantry) 0.149013)
    (= (nav-battery charge_main pantry) 0.116619)
    (= (nav-time charge_main fridge) 0.200238)
    (= (nav-battery charge_main fridge) 0.154029)
    (= (nav-time charge_main prep_station) 0.203961)
    (= (nav-battery charge_main prep_station) 0.152971)
    (= (nav-time charge_main stove) 0.230844)
    (= (nav-battery charge_main stove) 0.166208)
    (= (nav-time charge_main quality_check) 0.195556)
    (= (nav-battery charge_main quality_check) 0.160000)
    (= (nav-time charge_main patient_bed_left) 0.226177)
    (= (nav-battery charge_main patient_bed_left) 0.188481)
    (= (nav-time charge_main patient_bed_right) 0.253211)
    (= (nav-battery charge_main patient_bed_right) 0.211009)
    (= (nav-time charge_backup pantry) 0.493063)
    (= (nav-battery charge_backup pantry) 0.385876)
    (= (nav-time charge_backup fridge) 0.549894)
    (= (nav-battery charge_backup fridge) 0.422995)
    (= (nav-time charge_backup prep_station) 0.555058)
    (= (nav-battery charge_backup prep_station) 0.416293)
    (= (nav-time charge_backup stove) 0.602568)
    (= (nav-battery charge_backup stove) 0.433849)
    (= (nav-time charge_backup quality_check) 0.506449)
    (= (nav-battery charge_backup quality_check) 0.414367)
    (= (nav-time charge_backup patient_bed_left) 0.362442)
    (= (nav-battery charge_backup patient_bed_left) 0.302035)
    (= (nav-time charge_backup patient_bed_right) 0.344935)
    (= (nav-battery charge_backup patient_bed_right) 0.287446)

    ; Battery needed from each modeled location to reach the nearest charger.
    (= (nearest-charger-battery home) 0.0583)
    (= (nearest-charger-battery pantry) 0.1166)
    (= (nearest-charger-battery fridge) 0.1540)
    (= (nearest-charger-battery prep_station) 0.1530)
    (= (nearest-charger-battery stove) 0.1662)
    (= (nearest-charger-battery quality_check) 0.1600)
    (= (nearest-charger-battery patient_bed_left) 0.1885)
    (= (nearest-charger-battery patient_bed_right) 0.2110)
    (= (nearest-charger-battery charge_main) 0.0000)
    (= (nearest-charger-battery charge_backup) 0.0000)
    ; Numeric location features used by stage_cost.
    ; Safety feature: inverse-distance score from each location to its nearest
    ; modeled neighbor, normalized to the existing [0.05, 0.70] planner range.
    (= (location-safety home) 0.3455)
    (= (approach-feature home) 0.0000)
    (= (proximity-feature home) 0.3000)
    (= (location-safety pantry) 0.5361)
    (= (approach-feature pantry) 0.0000)
    (= (proximity-feature pantry) 0.3000)
    (= (location-safety fridge) 0.5361)
    (= (approach-feature fridge) 0.0000)
    (= (proximity-feature fridge) 0.3000)
    (= (location-safety prep_station) 0.7000)
    (= (approach-feature prep_station) 0.0000)
    (= (proximity-feature prep_station) 0.3000)
    (= (location-safety stove) 0.7000)
    (= (approach-feature stove) 0.0000)
    (= (proximity-feature stove) 0.3000)
    (= (location-safety quality_check) 0.6717)
    (= (approach-feature quality_check) 0.0000)
    (= (proximity-feature quality_check) 0.3000)
    ; Patient approach side tradeoff:
    ; left has better approach cost, right has better safety cost.
    (= (location-safety patient_bed_left) 0.7000)
    (= (approach-feature patient_bed_left) 0.0500)
    (= (proximity-feature patient_bed_left) 0.0500)
    (= (location-safety patient_bed_right) 0.0500)
    (= (approach-feature patient_bed_right) 0.7000)
    (= (proximity-feature patient_bed_right) 0.1000)
    (= (location-safety charge_main) 0.3455)
    (= (approach-feature charge_main) 0.0000)
    (= (proximity-feature charge_main) 0.3000)
    (= (location-safety charge_backup) 0.0500)
    (= (approach-feature charge_backup) 0.0000)
    (= (proximity-feature charge_backup) 0.3000)
    (= (approach-feature bedside_table_left) 0.0500)
    (= (approach-feature bedside_table_right) 0.7000)

    ; Preference weights: w0=time, w1=safety, w2=battery, w4=approach.
    (= (w0 robot1) 1)
    (= (w1 robot1) 1)
    (= (w2 robot1) 1)
    (= (w3 robot1) 1)
    (= (w4 robot1) 1)

    (= (battery-soc robot1) 1.0)

    ; In-place action durations.
    (= (collect_duration) 0.1667)
    (= (check_duration) 0.1333)
    (= (sanitize_duration) 0.1667)
    (= (wash_duration) 0.2000)
    (= (chop_duration) 0.2667)
    (= (cook_duration) 0.4000)
    (= (assemble_duration) 0.1667)
    (= (deliver-time) 0.3333)
    (= (duration-recharge) 1.0000)

    ; In-place action battery costs.
    (= (battery-collect_ingredient) 0.0200)
    (= (battery-check_ingredients) 0.0100)
    (= (battery-sanitize_workspace) 0.0200)
    (= (battery-wash_ingredients) 0.0200)
    (= (battery-chop_ingredients) 0.0300)
    (= (battery-cook_meal) 0.5000)
    (= (battery-check_cooking_level) 0.0100)
    (= (battery-check_palatability) 0.0100)
    (= (battery-assembla) 0.0200)
    (= (battery-deliver_on_bedside_table) 0.0100)

    (at robot1 home)

    ; Meal options. Only hot_meal requires the cook_meal action.
    (cold_meal sandwich)
    (cold_meal salad)
    (requires_cooking hot_meal)

    (pantry-location pantry)
    (fridge-location fridge)
    (prep-station-location prep_station)
    (cooking-station stove)
    (quality-check-location quality_check)
    (charger-location charge_main)
    (charger-location charge_backup)
    (main-charger charge_main)
    (backup-charger charge_backup)
    (patient-location patient_bed_left)
    (patient-left-location patient_bed_left)
    (patient-location patient_bed_right)
    (patient-right-location patient_bed_right)

    (required_ingredient sandwich bread)
    (required_ingredient sandwich vegetables)
    (required_ingredient salad nuts)
    (required_ingredient salad vegetables)
    (required_ingredient hot_meal chicken)
    (required_ingredient hot_meal vegetables)

    (missing_ingredient robot1 bread)
    (missing_ingredient robot1 nuts)
    (missing_ingredient robot1 chicken)
    (missing_ingredient robot1 vegetables)

    (ingredient_available pantry bread)
    (ingredient_available pantry nuts)
    (ingredient_available pantry vegetables)
    (ingredient_available fridge chicken)
  )

  (:goal
    (and
      (meal_palatable robot1)
      (meal_assembled robot1)
      (delivered robot1)
    )
  )

  ; Equivalent to MinimizeExpressionOnFinalState:
  ; stage_cost + total_time*w0 + 0.1*discrete_steps.
  (:metric minimize
    (+ (stage_cost)
      (+ (* (total_time) (w0 robot1))
         (* 0.1 (discrete_steps)))))
)
